name: Convert LaTeX to HTML with Sphinx and Compile PDF

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

permissions:
  contents: write  # Grant write access to the GitHub Actions bot

jobs:
  compile_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install LaTeX
        run: sudo apt-get install -y texlive-full  # Install LaTeX

      - name: Compile LaTeX to PDF
        run: pdflatex main.tex  # Compile the LaTeX file to PDF

      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pdf
          path: ./main.pdf  # Adjust the path if your LaTeX file is in a subfolder

      - name: Commit and push compiled PDF
        run: |
          git config --local user.email "katieh@unis.no"  # Your email
          git config --local user.name "kherli"  # Your name
          git add main.pdf
          git commit -m "Add compiled PDF"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  sphinx:
    needs: compile_pdf  # Ensure this job runs after the PDF compilation job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo rm /etc/apt/apt-mirrors.txt || true  # Remove the mirrors file if it exists
          sudo apt-get update  # Update the package list
          sudo apt-get install -y python3 python3-pip pandoc pandoc-citeproc  # Install Pandoc and pandoc-citeproc
          pip3 install sphinx sphinx-wagtail-theme sphinxcontrib-bibtex  # Install Sphinx and BibTeX extension

      - name: Verify Installed Packages
        run: pip3 list  # This will list all installed Python packages

      - name: Clean Build Directory
        run: rm -rf docs/build/html  # Clean previous builds

      - name: Create docs/source Directory
        run: mkdir -p docs/source  # Create a docs/source directory if it doesn't exist

      - name: Initialize Sphinx Documentation
        run: |
          cd docs
          sphinx-quickstart --quiet --sep --project="Handbook" --author="ARCTICS" --release="0.1" --language="en" --makefile

      - name: Convert LaTeX to RST with Bibliography
        run: |
          pandoc main.tex --bibliography=references.bib --filter pandoc-citeproc -o docs/source/main.rst  # Convert your LaTeX file to RST format with bibliography

      - name: Create Master Document (index.rst)
        run: |
          echo "**Hello and Welcome!**" > docs/source/index.rst  # Make the title bold
          echo "" >> docs/source/index.rst
          echo "We are a team of scientists and citizen scientists, all united by a shared passion for the aurora! Together, in the \`Auroral Research Coordination: Towards Internationalised Citizen Science (ARCTICS) <https://collab.issibern.ch/arctics/>\`_ group, we’ve combined our expertise to create two valuable resources for the aurora community." >> docs/source/index.rst
          echo "" >> docs/source/index.rst
          echo "Our Aurora Field Guide provides examples of various types of auroras, helping you recognize and identify different forms in your own photographs. Meanwhile, our Aurora Handbook delves deeper into aurora chasing, capturing images for scientific research, and contributing to our collective understanding. We explain the process of taking and submitting your photos, how collaborations between professional scientists and citizen scientists unfold, and highlight key discoveries that have emerged through this teamwork." >> docs/source/index.rst
          echo "" >> docs/source/index.rst
          echo "These guides are available to you free of charge, and we hope that you enjoy them! Happy aurora hunting from the ARCTICS team!" >> docs/source/index.rst
          echo "" >> docs/source/index.rst
          echo "" >> docs/source/index.rst
          echo "Both guides are licensed under a Creative Commons Attribution-NonCommercial 4.0 International License (CC BY-NC 4.0), and we ask that if you cite them to use the following DOI:" >> docs/source/index.rst  
          echo ".. raw:: html" >> docs/source/index.rst
          echo "" >> docs/source/index.rst
          echo "   <a href='https://zenodo.org/doi/10.5281/zenodo.13837258'><img src='https://zenodo.org/badge/862822419.svg' alt='DOI'></a>" >> docs/source/index.rst
          echo "" >> docs/source/index.rst          
          echo "Happy aurora hunting from the ARCTICS team!" >> docs/source/index.rst
          echo "" >> docs/source/index.rst
          echo "**Aurora Field Guide for Citizen Science**" >> docs/source/index.rst  # Add bold section title
          echo "" >> docs/source/index.rst
          echo ".. image:: _static/Field_Guide_Cover.jpg" >> docs/source/index.rst  # Add image from static folder
          echo "   :alt: Aurora Field Guide Cover" >> docs/source/index.rst
          echo "   :align: center" >> docs/source/index.rst
          echo "" >> docs/source/index.rst
          echo "\`Click Here for the Aurora Field Guide <_static/Aurora_Field_Guide.pdf>\`_" >> docs/source/index.rst
          echo "" >> docs/source/index.rst
          echo "**Aurora Handbook for Citizen Science**" >> docs/source/index.rst  # Add bold section title for the Handbook
          echo "" >> docs/source/index.rst
          echo ".. image:: _static/Handbook_Cover.jpg" >> docs/source/index.rst  # Add handbook image
          echo "   :alt: Aurora Handbook Cover" >> docs/source/index.rst
          echo "   :align: center" >> docs/source/index.rst
          echo "" >> docs/source/index.rst
          echo ".. toctree::" >> docs/source/index.rst
          echo "   :maxdepth: 2" >> docs/source/index.rst
          echo "   :caption: **Contents**:" >> docs/source/index.rst
          echo "" >> docs/source/index.rst
          echo "   main" >> docs/source/index.rst

      - name: Copy Images to _static
        run: |
          mkdir -p docs/source/_static  # Ensure _static directory exists
          cp Field_Guide_Cover.jpg docs/source/_static/  # Copy Field Guide image from root to _static directory
          cp Handbook_Cover.jpg docs/source/_static/  # Copy Handbook image from root to _static directory
          cp Aurora_Field_Guide.pdf docs/source/_static/  # Copy PDF from root to _static directory

      - name: Configure Sphinx for BibTeX
        run: |
          echo 'extensions.append("sphinx_wagtail_theme")' >> docs/source/conf.py  # Enable Wagtail theme
          echo 'html_theme = "sphinx_wagtail_theme"' >> docs/source/conf.py  # Set Wagtail theme
          echo 'extensions = ["sphinx.ext.imgmath", "sphinx_wagtail_theme", "sphinxcontrib.bibtex"]' >> docs/source/conf.py  # Add required extensions

      - name: Build Sphinx Documentation
        run: |
          cd docs
          make html  # Build HTML documentation

      - name: Deploy Documentation to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html  # Change if necessary
