name: Convert LaTeX to HTML with Sphinx

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

permissions:
  contents: write  # Grant write access to the GitHub Actions bot

jobs:
  sphinx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip pandoc pandoc-citeproc  # Install Pandoc and pandoc-citeproc
          pip3 install sphinx sphinx-wagtail-theme sphinxcontrib-bibtex pandoc-crossref  # Install Sphinx, BibTeX, and Crossref extension

      - name: Verify Installed Packages
        run: pip3 list  # This will list all installed Python packages

      - name: Clean Build Directory
        run: rm -rf docs/build/html  # Clean previous builds

      - name: Create docs/source Directory
        run: mkdir -p docs/source  # Create a docs/source directory if it doesn't exist

      - name: Initialize Sphinx Documentation
        run: |
          cd docs
          sphinx-quickstart --quiet --sep --project="Handbook" --author="ARCTICS" --release="0.1" --language="en" --makefile

      - name: Convert LaTeX to RST with Bibliography and Cross References
        run: |
          pandoc main.tex --bibliography=references.bib --filter pandoc-citeproc --filter pandoc-crossref -o docs/source/main.rst  # Convert LaTeX to RST with bibliography and cross-referencing

      - name: Create Master Document (index.rst)
        run: |
          echo "Welcome to My Project's documentation!" > docs/source/index.rst
          echo "" >> docs/source/index.rst
          echo ".. toctree::" >> docs/source/index.rst
          echo "   :maxdepth: 2" >> docs/source/index.rst
          echo "   :caption: Contents:" >> docs/source/index.rst
          echo "" >> docs/source/index.rst
          echo "   main" >> docs/source/index.rst

      - name: Configure Sphinx for Figure Numbering
        run: |
          echo 'extensions.append("sphinx_wagtail_theme")' >> docs/source/conf.py  # Enable Wagtail theme
          echo 'html_theme = "sphinx_wagtail_theme"' >> docs/source/conf.py  # Set Wagtail theme
          echo 'extensions = ["sphinx.ext.imgmath", "sphinx_wagtail_theme", "sphinxcontrib.bibtex"]' >> docs/source/conf.py  # Enable LaTeX for images and BibTeX support
          echo 'bibtex_bibfiles = ["../../references.bib"]' >> docs/source/conf.py  # Point to the .bib file in the root directory
          echo 'html_static_path = ["_static"]' >> docs/source/conf.py  # Specify the static path
          echo 'html_baseurl = "https://kherli.github.io/Testing/"' >> docs/source/conf.py  # Add the base URL for GitHub Pages
          echo 'master_doc = "index"' >> docs/source/conf.py  # Set the master document

          # Enable figure numbering and format
          echo 'numfig = True' >> docs/source/conf.py  # Enable figure numbering
          echo 'numfig_format = {"figure": "Figure %s:", "table": "Table %s:", "code-block": "Listing %s:"}' >> docs/source/conf.py  # Customize figure caption format

      - name: Ensure _static Directory Exists
        run: mkdir -p docs/source/_static  # Create _static directory if it doesn't exist

      - name: Build Sphinx Documentation
        run: |
          cd docs
          make html SPHINXOPTS="-v"  # Build the HTML documentation

      - name: List HTML Build Directory
        run: |
          cd docs
          ls -la build/html  # List contents of the HTML build directory

      - name: List Static Directory Contents
        run: |
          cd docs/build/html/_static
          ls -la  # List contents of the _static directory

      - name: Check Generated HTML Content
        run: |
          cd docs
          cat build/html/index.html  # Output the contents of the index.html for inspection

      - name: Commit and push to gh-pages
        run: |
          git config --local user.email "katieh@unis.no"  # Your email
          git config --local user.name "kherli"  # Your name

          # Create or switch to gh-pages branch
          git checkout -B gh-pages  # Creates the branch if it doesn't exist or resets it

          # Copy generated HTML to the root of the gh-pages branch
          cp -R docs/build/html/* ./  # Copies the built files

          # Add and commit the changes
          git add .
          git commit -m "Deploy Sphinx documentation" || echo "No changes to commit"  # Prevent errors if no changes

          # Push changes to the gh-pages branch
          git push --force origin gh-pages  # Use --force to overwrite if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
