name: Generate Documentation with Sphinx

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

permissions:
  contents: write  # Grant write access to the GitHub Actions bot

jobs:
  sphinx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip pandoc  # Install Pandoc
          pip3 install sphinx  # Install Sphinx
          
          # Install Sphinx Wagtail theme using the GitHub token for authentication
          pip3 install git+https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/wagtail/sphinx-wagtail-theme

      - name: Convert .tex to .rst
        run: |
          pandoc main.tex -o main.rst  # Convert your .tex file to .rst format
          mkdir -p docs  # Create a docs directory if it doesn't exist
          cp main.rst docs/  # Copy your .rst file to the docs directory

      - name: Build Sphinx Documentation
        run: |
          cd docs
          # Make sure your conf.py is correctly configured
          echo 'html_theme = "sphinx_wagtail_theme"' >> conf.py  # Set Wagtail theme
          echo 'html_theme_path = []' >> conf.py  # Set the theme path to default

          # Build the documentation
          make html  # Build the documentation

      - name: Commit and push to gh-pages
        run: |
          git config --local user.email "katieh@unis.no"  # Your email
          git config --local user.name "kherli"  # Your name

          # Create or switch to gh-pages branch
          git checkout -B gh-pages  # Creates the branch if it doesn't exist or resets it

          # Copy generated HTML to the root of the gh-pages branch
          cp -R docs/_build/html/* ./  # Copies the built files

          # Add and commit the changes
          git add .
          git commit -m "Deploy Sphinx documentation" || echo "No changes to commit"  # Prevent errors if no changes

          # Push changes to the gh-pages branch
          git push --force origin gh-pages  # Use --force to overwrite if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
