name: Generate Documentation with Sphinx

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

permissions:
  contents: write  # Grant write access to the GitHub Actions bot

jobs:
  sphinx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip pandoc  # Install Pandoc
          pip3 install sphinx  # Install Sphinx
          pip install sphinx-material  # Install Material theme

      - name: Initialize Sphinx Documentation
        run: |
          mkdir -p docs/source  # Create a docs/source directory if it doesn't exist
          cd docs
          sphinx-quickstart --quiet --sep --project="My Project" --author="Your Name" --release="0.1" --language="en" --makefile

      - name: Convert .tex to .rst
        run: |
          pandoc main.tex -o docs/source/main.rst  # Convert your .tex file to .rst format and place in source

      - name: Check docs Directory
        run: |
          ls -la docs  # List contents of the docs directory
          ls -la docs/source  # List contents of the source directory

      - name: Build Sphinx Documentation
        run: |
          cd docs
          # Ensure your conf.py is correctly configured
          echo 'html_theme = "sphinx_material"' >> source/conf.py  # Set Material theme in conf.py
          
          # Build the documentation
          make html

      - name: List HTML Build Directory
        run: |
          cd docs
          ls -la build/html  # List contents of the HTML build directory

      - name: Commit and push to gh-pages
        run: |
          git config --local user.email "katieh@unis.no"  # Your email
          git config --local user.name "kherli"  # Your name

          # Create or switch to gh-pages branch
          git checkout -B gh-pages  # Creates the branch if it doesn't exist or resets it

          # Copy generated HTML to the root of the gh-pages branch
          cp -R build/html/* ./  # Copies the built files

          # Add and commit the changes
          git add .
          git commit -m "Deploy Sphinx documentation" || echo "No changes to commit"  # Prevent errors if no changes

          # Push changes to the gh-pages branch
          git push --force origin gh-pages  # Use --force to overwrite if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
