name: Generate Documentation with Sphinx

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

permissions:
  contents: write  # Grant write access to the GitHub Actions bot

jobs:
  sphinx:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip pandoc  # Install Pandoc
          pip3 install sphinx  # Install Sphinx
          pip install sphinx-material  # Install Material theme

      - name: Initialize Sphinx Documentation
        run: |
          mkdir -p docs  # Create a docs directory if it doesn't exist
          cd docs
          sphinx-quickstart --quiet --sep --project="My Project" --author="Your Name" --release="0.1" --language="en" --makefile

      - name: Add Minimal Content to index.rst
        run: |
          echo "Welcome to the Documentation!" > docs/index.rst
          echo "" >> docs/index.rst
          echo "This is a simple test to see if content is rendering correctly." >> docs/index.rst

      - name: Build Sphinx Documentation
        run: |
          cd docs
          echo 'html_theme = "sphinx_material"' >> conf.py  # Set Material theme
          echo 'master_doc = "index"' >> conf.py  # Set master doc
          make html SPHINXOPTS="-v"  # Verbose mode for detailed logs

      - name: Check Generated HTML Content
        run: |
          cat docs/build/html/index.html  # Output the contents of index.html for inspection

      - name: Verify Build Output
        run: |
          cd docs/build/html
          ls -la  # List the contents of the HTML build directory, ensuring files are present

      - name: Commit and push to gh-pages
        run: |
          git config --local user.email "katieh@unis.no"  # Your email
          git config --local user.name "kherli"  # Your name

          # Create or switch to gh-pages branch
          git checkout -B gh-pages  # Creates the branch if it doesn't exist or resets it

          # Copy generated HTML to the root of the gh-pages branch
          cp -R docs/build/html/* ./  # Copies the built files

          # Add and commit the changes
          git add .
          git commit -m "Deploy Sphinx documentation" || echo "No changes to commit"  # Prevent errors if no changes

          # Push changes to the gh-pages branch
          git push --force origin gh-pages  # Use --force to overwrite if needed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the GitHub token for authentication
